#!/bin/sh
#
# Usage: gputest.sh
# Change job name and email address as needed 
#        
# -- our name ---
#$ -N dp
#$ -S /bin/sh
# Make sure that the .e and .o file arrive in the
#working directory
#$ -cwd
#Merge the standard out and standard error to one file
#$ -j y
# Request a gpu

#$ -q datasci

/bin/echo Running on host: `hostname`.
/bin/echo In directory: `pwd`
/bin/echo Starting on: `date`
 
# Load openmp module
. /opt/modules/init/bash


module load cuda
module load singularity

singularity exec --nv /opt/singularity_images/deeplearning_cuda_10.1_ubuntu-16.04_python-3.6_v1.2.sif python3 train.py test mlp20node_model Attack > log_train
