#!/bin/sh
#
# Usage: gputest.sh
# Change job name and email address as needed 
#        
# -- our name ---
#$ -N dp
#$ -S /bin/sh
# Make sure that the .e and .o file arrive in the
#working directory
#$ -cwd
#Merge the standard out and standard error to one file
#$ -j y
# Request a gpu

#$ -q datasci

/bin/echo Running on host: `hostname`.
/bin/echo In directory: `pwd`
/bin/echo Starting on: `date`
 
# Load openmp module
. /opt/modules/init/bash
module load intel/compiler/2017.2.174

#module load gsl-gnu4
#export LD_LIBRARY_PATH=/opt/gsl/1.15/gnu4/lib:$LD_LIBRARY_PATH

#Full path to executable
#Replace usman's home directory path with yours in the command below

/usr/bin/time -f %e -o time_openmp ./dp_openmp 3 3 ./test_matrix ./test_vector 10 > output_openmp
#/usr/bin/time -f %e -o chi2time_gpu /home/u/usman/courses/cs677_spring19/Chi2/Chi2 /home/u/usman/courses/cs677_spring19/Chi2/traindata 8000 29623 4000 4000 0 256 > output_gpu
#/usr/bin/time -f %e -o chi2time_gpu2 /home/u/usman/courses/cs677_spring19/Chi2/Chi2 /home/u/usman/courses/cs698_spring18/data_fixed_.01 4901 422006 1963 2938 0 512 > output_gpu2

#/usr/bin/time -f %e -o chi2time_serial /home/u/usman/courses/cs677_spring19/Chi2/Chi2_serial /home/u/usman/courses/cs677_spring19/Chi2/traindata 8000 29623 4000 4000 > output_serial
#/usr/bin/time -f %e -o chi2time_serial2 /home/u/usman/courses/cs677_spring19/Chi2/Chi2_serial /home/u/usman/courses/cs698_spring18/data_fixed_.01 4901 422006 1963 2938 > output_serial2

